# This manifest is for core services that are only required when running on AWS.
kapps:

  # The `kiam` chart will be installed into the `kiam` namespace, the release
  # will also be called `kiam`. The version number will be set to the version
  # extracted from `Charts.yaml` in `charts/stable/kiam/`. No `installer` block
  # is defined so defaults are used.
  kiam:
    state: present
    sources:
      kapp:
        uri: git@github.com:sugarkube/kapps.git
        branch: master
        #      branch: kiam-0.1.0
        path: incubator/kiam/
      makefiles:
        uri: git@github.com:sugarkube/kapps.git
        branch: master
        path: incubator/common-makefiles
