# This manifest contains kapps that represent the actual products you're shipping,
# in this case web sites.

# Kapps listed under this key will be installed if they are not currently
# installed in the target cluster.
present:
  # This entry demonstrates how to explicitly declare values.
  #
  # Unique identifier. The same kapp can be installed multiple times provided
  # this is unique per instance. This will be the release name when using Helm.
  - id: wordpress-site1
    templates:        # a list of templates to render for this kapp
#      - source: terraform/backend.tf  # source template must exist under one of the
                                      # 'template' directories declared in the stacks.yaml file
#        dest: wordpress/_generated_backend.tf   # dest relative to the kapp root directory

    # Sources to checkout as siblings in the cache for this kapp. This allows
    # creating a cache entry from e.g. the actual kapp source, a directory of
    # shared makefiles, and/or pulling in `values.yaml` files etc. from a
    # separately versioned source.
    sources:
    - uri: git@github.com:sugarkube/kapps.git
      branch: master
      # the name of this source defaults to `wordpress` because it's the last
      # component of the path. The name can also be set explicitly as
      # illustrated below.
      path: incubator/wordpress
#      includeValues: false    # don't search this source for helm/terraform values
# todo - implement these paths and uncomment as an example
#    - uri: git@github.com:sugarkube/sugarkube.git
#      branch: master
#      # this lets us reuse the same kapp parameterised differently per instance
#      path: examples/values/wordpress/site1/
#      # Name of the source. Defaults to the last component of the path (in this
#      # case `site1`). Also used as a key.
#      id: site1-values
    - uri: git@github.com:sugarkube/kapps.git
      branch: master
      path: incubator/common-makefiles
    - uri: git@github.com:sugarkube/sample-project.git
      branch: master
      path: demo-data/wordpress/site1
      id: data

  - id: wordpress-site2
    sources:
    - uri: git@github.com:sugarkube/kapps.git
      branch: master
      #branch: wordpress-0.1.0
      path: incubator/wordpress
      id: wp-kapp
    - uri: git@github.com:sugarkube/kapps.git
      branch: master
      path: incubator/common-makefiles
    - uri: git@github.com:sugarkube/sample-project.git
      branch: master
      path: demo-data/wordpress/site2
      id: data
