kube_context: minikube          # todo - this should be an overrideable default for this provider

# todo - decide where to put this. It'd be nice to use xip.io, but how can we
# inject the cluster IP?
hosted_zone: localhost            # The domain to host your stuff under.

# Values passed to `minikube start`. Underscores are converted to hyphens and
# values keys prepended with two dashes. So e.g. `disk_size` is passed as `--disk-size`.
provisioner:
  params:
    start:        # parameters for the `minikube start` command
      bootstrapper: kubeadm
      memory: 2048
      cpus: 2
      disk_size: 30g
